### ISSUE TITLE
about input data size

### ISSUE THREAD

**Issue by haleyfid** [atiyo/deep_image_prior#2]
hi,
I am a student 
I want to input a 600x600 size picture as input
but it requires 512x512 size input 
can you help me that where can I change about input size from 512x512 to 600x600?

**Comment by atiyo** [comment]
hi there,

sorry for the late response.

if you don't mind simply resizing the image, that would be easiest. you could do so from within the script by adding in `pil = pil.resize([512,512])` after line 28 in `deep_image_prior.py`. 

the architectures were really designed with 512x512 images in mind. to make things natively work with 600x600 images, a new architecture would be needed. maybe you can use the current ones defined within the script as a guide?

i hope that helps.

**Comment by atiyo** [comment]
closing this one now. please do reopen if you have further questions.
